services:
  app:
    build: .
    ports:
      - "80:3000"
      - "3000:3000"
    env_file: .env
    volumes:
      - ./sessions:/sessions
    restart: always

# Serviço do MongoDB Local REMOVIDO para economizar RAM da VPS (Usando MongoDB Atlas na Nuvem)
